/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Accounts": {
    get: {
      parameters: {
        query: {
          account_id?: parameters["rowFilter.Accounts.account_id"];
          created_at?: parameters["rowFilter.Accounts.created_at"];
          name?: parameters["rowFilter.Accounts.name"];
          budget_limit?: parameters["rowFilter.Accounts.budget_limit"];
          categories?: parameters["rowFilter.Accounts.categories"];
          belongs_to_user?: parameters["rowFilter.Accounts.belongs_to_user"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Accounts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Accounts */
          Accounts?: definitions["Accounts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          account_id?: parameters["rowFilter.Accounts.account_id"];
          created_at?: parameters["rowFilter.Accounts.created_at"];
          name?: parameters["rowFilter.Accounts.name"];
          budget_limit?: parameters["rowFilter.Accounts.budget_limit"];
          categories?: parameters["rowFilter.Accounts.categories"];
          belongs_to_user?: parameters["rowFilter.Accounts.belongs_to_user"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          account_id?: parameters["rowFilter.Accounts.account_id"];
          created_at?: parameters["rowFilter.Accounts.created_at"];
          name?: parameters["rowFilter.Accounts.name"];
          budget_limit?: parameters["rowFilter.Accounts.budget_limit"];
          categories?: parameters["rowFilter.Accounts.categories"];
          belongs_to_user?: parameters["rowFilter.Accounts.belongs_to_user"];
        };
        body: {
          /** Accounts */
          Accounts?: definitions["Accounts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/Transactions": {
    get: {
      parameters: {
        query: {
          transaction_id?: parameters["rowFilter.Transactions.transaction_id"];
          created_at?: parameters["rowFilter.Transactions.created_at"];
          amount?: parameters["rowFilter.Transactions.amount"];
          store?: parameters["rowFilter.Transactions.store"];
          category?: parameters["rowFilter.Transactions.category"];
          account_id?: parameters["rowFilter.Transactions.account_id"];
          trans_date?: parameters["rowFilter.Transactions.trans_date"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Transactions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Transactions */
          Transactions?: definitions["Transactions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          transaction_id?: parameters["rowFilter.Transactions.transaction_id"];
          created_at?: parameters["rowFilter.Transactions.created_at"];
          amount?: parameters["rowFilter.Transactions.amount"];
          store?: parameters["rowFilter.Transactions.store"];
          category?: parameters["rowFilter.Transactions.category"];
          account_id?: parameters["rowFilter.Transactions.account_id"];
          trans_date?: parameters["rowFilter.Transactions.trans_date"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          transaction_id?: parameters["rowFilter.Transactions.transaction_id"];
          created_at?: parameters["rowFilter.Transactions.created_at"];
          amount?: parameters["rowFilter.Transactions.amount"];
          store?: parameters["rowFilter.Transactions.store"];
          category?: parameters["rowFilter.Transactions.category"];
          account_id?: parameters["rowFilter.Transactions.account_id"];
          trans_date?: parameters["rowFilter.Transactions.trans_date"];
        };
        body: {
          /** Transactions */
          Transactions?: definitions["Transactions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Accounts: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    account_id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name?: string;
    /** Format: double precision */
    budget_limit?: number;
    /** Format: json */
    categories?: string;
    /** Format: text */
    belongs_to_user?: string;
  };
  Transactions: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    transaction_id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: double precision */
    amount?: number;
    /** Format: text */
    store?: string;
    /** Format: text */
    category?: string;
    /** Format: text */
    account_id?: string;
    /** Format: date */
    trans_date?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Accounts */
  "body.Accounts": definitions["Accounts"];
  /** Format: bigint */
  "rowFilter.Accounts.account_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Accounts.created_at": string;
  /** Format: text */
  "rowFilter.Accounts.name": string;
  /** Format: double precision */
  "rowFilter.Accounts.budget_limit": string;
  /** Format: json */
  "rowFilter.Accounts.categories": string;
  /** Format: text */
  "rowFilter.Accounts.belongs_to_user": string;
  /** @description Transactions */
  "body.Transactions": definitions["Transactions"];
  /** Format: bigint */
  "rowFilter.Transactions.transaction_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Transactions.created_at": string;
  /** Format: double precision */
  "rowFilter.Transactions.amount": string;
  /** Format: text */
  "rowFilter.Transactions.store": string;
  /** Format: text */
  "rowFilter.Transactions.category": string;
  /** Format: text */
  "rowFilter.Transactions.account_id": string;
  /** Format: date */
  "rowFilter.Transactions.trans_date": string;
}

export interface operations {}

export interface external {}
